version: "3.8"
services: 
  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  server:
    image: "amosbastian/nextjs-graphql-starter:latest"
    depends_on: 
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
    ports:
      - "3333:3333"
